//
//  ClipboardManager.swift
//  boringNotch
//
//  Следит за системным буфером обмена и хранит историю (текст, картинки, файлы).
//  Не сохраняет то, что приложения помечают как секретное (менеджеры паролей).
//

import AppKit
import Combine
import CryptoKit
import Foundation

final class ClipboardManager: ObservableObject {
    static let shared = ClipboardManager()

    @Published private(set) var items: [ClipboardItem] = []
    @Published var isPaused = false {
        didSet { UserDefaults.standard.set(isPaused, forKey: "clipboardPaused") }
    }

    private let maxUnpinned = 60
    private let maxImages = 25
    private let maxTextLength = 20_000

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private var saveWorkItem: DispatchWorkItem?

    /// Приложения, из которых буфер не сохраняем (менеджеры паролей).
    private let ignoredBundleIDs: Set<String> = [
        "com.1password.1password", "com.agilebits.onepassword7", "com.agilebits.onepassword-osx",
        "com.bitwarden.desktop", "org.keepassxc.keepassxc", "com.apple.keychainaccess",
        "com.apple.Passwords", "com.lastpass.LastPass", "com.dashlane.dashlanephonefinal",
    ]
    private let skippedTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
    ]

    private let storageDir: URL = {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        let dir = base.appendingPathComponent("BoringNotchClipboard", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }()
    private var historyURL: URL { storageDir.appendingPathComponent("history.json") }

    private init() {
        lastChangeCount = pasteboard.changeCount
        isPaused = UserDefaults.standard.bool(forKey: "clipboardPaused")
        load()
        timer = Timer.scheduledTimer(withTimeInterval: 0.6, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    // MARK: - Слежение за буфером

    private func poll() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        guard !isPaused else { return }

        let types = pasteboard.types ?? []
        if types.contains(where: { skippedTypes.contains($0) }) { return }
        if let bundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier,
           ignoredBundleIDs.contains(bundleID) { return }
        let sourceApp = NSWorkspace.shared.frontmostApplication?.localizedName

        // 1) Файлы
        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            add(ClipboardItem(kind: .files, filePaths: urls.map { $0.path }, sourceApp: sourceApp))
            return
        }

        // 2) Картинка
        if let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff),
           let png = Self.pngData(from: data) {
            let name = Self.fileName(for: png)
            let url = storageDir.appendingPathComponent(name)
            if !FileManager.default.fileExists(atPath: url.path) {
                try? png.write(to: url)
            }
            add(ClipboardItem(kind: .image, imageFileName: name, sourceApp: sourceApp))
            return
        }

        // 3) Текст
        if var text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            if text.count > maxTextLength { text = String(text.prefix(maxTextLength)) }
            add(ClipboardItem(kind: .text, text: text, sourceApp: sourceApp))
        }
    }

    private static func pngData(from data: Data) -> Data? {
        guard let rep = NSBitmapImageRep(data: data) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    private static func fileName(for data: Data) -> String {
        let digest = SHA256.hash(data: data)
        return digest.prefix(12).map { String(format: "%02x", $0) }.joined() + ".png"
    }

    private func add(_ item: ClipboardItem) {
        var new = item
        if let index = items.firstIndex(where: { $0.contentKey == item.contentKey }) {
            // Уже есть: поднимаем наверх, сохраняя закрепление.
            new.pinned = items[index].pinned
            items.remove(at: index)
        }
        items.insert(new, at: 0)
        trim()
        scheduleSave()
    }

    private func trim() {
        var unpinned = 0
        var images = 0
        var keep: [ClipboardItem] = []
        for item in items {
            if item.pinned { keep.append(item); continue }
            unpinned += 1
            if item.kind == .image { images += 1 }
            if unpinned <= maxUnpinned && !(item.kind == .image && images > maxImages) {
                keep.append(item)
            }
        }
        items = keep
        cleanupOrphanImages()
    }

    // MARK: - Действия пользователя

    /// Вернуть элемент в буфер обмена (потом можно вставить через ⌘V).
    func copyToPasteboard(_ item: ClipboardItem) {
        pasteboard.clearContents()
        switch item.kind {
        case .text:
            pasteboard.setString(item.text ?? "", forType: .string)
        case .files:
            let urls = (item.filePaths ?? []).map { URL(fileURLWithPath: $0) as NSURL }
            pasteboard.writeObjects(urls)
        case .image:
            if let image = image(for: item) { pasteboard.writeObjects([image]) }
        }
        lastChangeCount = pasteboard.changeCount
        // Поднимаем наверх, чтобы было видно, что скопировано последним.
        if let index = items.firstIndex(where: { $0.id == item.id }) {
            var moved = items.remove(at: index)
            moved.date = Date()
            items.insert(moved, at: 0)
            scheduleSave()
        }
    }

    func togglePin(_ item: ClipboardItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[index].pinned.toggle()
        scheduleSave()
    }

    func remove(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        cleanupOrphanImages()
        scheduleSave()
    }

    /// Очистить всё, кроме закреплённого.
    func clearUnpinned() {
        items = items.filter { $0.pinned }
        cleanupOrphanImages()
        scheduleSave()
    }

    // MARK: - Картинки

    private let imageCache = NSCache<NSString, NSImage>()

    func imageURL(for item: ClipboardItem) -> URL? {
        guard let name = item.imageFileName else { return nil }
        return storageDir.appendingPathComponent(name)
    }

    func image(for item: ClipboardItem) -> NSImage? {
        guard let name = item.imageFileName, let url = imageURL(for: item) else { return nil }
        if let cached = imageCache.object(forKey: name as NSString) { return cached }
        guard let image = NSImage(contentsOf: url) else { return nil }
        imageCache.setObject(image, forKey: name as NSString)
        return image
    }

    private func cleanupOrphanImages() {
        let used = Set(items.compactMap { $0.imageFileName })
        let files = (try? FileManager.default.contentsOfDirectory(atPath: storageDir.path)) ?? []
        for file in files where file.hasSuffix(".png") && !used.contains(file) {
            try? FileManager.default.removeItem(at: storageDir.appendingPathComponent(file))
        }
    }

    // MARK: - Хранение

    private func load() {
        guard
            let data = try? Data(contentsOf: historyURL),
            let decoded = try? JSONDecoder().decode([ClipboardItem].self, from: data)
        else { return }
        items = decoded
    }

    private func scheduleSave() {
        saveWorkItem?.cancel()
        let snapshot = items
        let url = historyURL
        let work = DispatchWorkItem {
            if let data = try? JSONEncoder().encode(snapshot) {
                try? data.write(to: url, options: .atomic)
            }
        }
        saveWorkItem = work
        DispatchQueue.global(qos: .utility).asyncAfter(deadline: .now() + 1, execute: work)
    }
}
